version: '3.7'
services:
  gg_bot:
    image: avvero/gg_bot:latest
    pull_policy: always
    container_name: gg_bot
    environment:
      - token=token
    ports:
      - "8066:8080"
    network_mode: "bridge"
